/* jslint node: true */
/* jslint esnext: true */

module.exports = [
    "Write a thoughtful note and slip it into your partner's work bag. ",
    'Ask your significant other, <break time="0.05s"/>"What can I do today to make you feel more loved?" ',
    'Fill in the blank and say to your partner, <break time="0.05s"/>"I am proud of the way you blank." ',
    'Fill in the blank and say to your partner, <break time="0.05s"/>"I am impressed that you blank." ',
    'Fill in the blank and say to your partner, <break time="0.05s"/>"I love how you blank." ',
    'Write a sticky note, starting with the words <break time="0.05s"/>"thank you for", and stick it somewhere your partner will see it. ',
    'Next time you ask, <break time="0.05s"/>"How was your day?", really listen to the answer. ',
    'Do one chore around the house that, on an ordinary day, your partner would normally do instead. ',
    "Go for a short walk together when you're both home from work. ",
    "Make tonight an unexpected date night, even if it's just going to the neighborhood pub. ",
    'Take a romantic drive in a new neighborhood this evening. ',
    'Dream about the next big trip you hope to take together. ',
    'Let your significant other pick the next show you watch. ',
    'Offer to help your partner with a specific household chore, without them asking first. ',
    'If your partner is having a tough week, tell them, <break time="0.05s"/>"I am here for you." ',
    "Make sure to ask your partner about something that isn't a chore, an appointment, or other administrative task. ",
    'Reminisce with your significant other about one of your favorite date nights you two shared. ',
    'Ask your partner, <break time="0.05s"/>"What do you remember most about when we first started dating?" ',
    'When you two first started dating, what stood out about your significant other? Tell them what you remember most about them. ',
    "This evening, bring home your partner's favorite snack. ",
    'Reminisce about a vacation you two took together. ',
    'If you can, praise your partner in front of someone else, like a mutual friend, a child, or a parent. ',
    "Instead of grabbing breakfast on the way out, wake up a few minutes early and bring breakfast to your partner in bed. If it's too late today, try this tomorrow. ",
    'What moments stand out as the high points in your relationship so far? <break time="0.05s"/>Pick one of them and reminisce about it with your partner. ',
    "Pack your partner's favorite snack or drink in their work bag. ",
    'Give your partner an extra hug today. ',
    'Send your signifcant other a loving text message today for no reason. ',
    'Keep an eye out for a small gift, <break time="0.05s"/>maybe a snack or a trinket, that reminds you of your partner. ',
    "It's easy to notice the things our partners do wrong. Instead, pay extra close attention to the things your partner does right today. ",
    "Brew an extra cup of coffee or tea and bring it to your partner while they're still in bed. ",
    'Make a Spotify playlist just for the two of you. ',
    'Make up a secret handshake. ',
    'When your partner gets home, greet them at the door. ',
    'Ask your partner to explain a hobby of theirs. ',
    'Let your partner know how great they look. ',
    'Text your significant other a photo of your day, like the view from your office desk, or something interesting you saw on the way home from work. ',
    'Ask your partner, "What can I do for you to make today a little less stressful?" ',
    "See something beautiful together, whether it's a sunset, the moon, or just the view outside your home. ",
    'Dig up a souvenir from earlier in your relationship, like a photograph, or an old ticket stub. ',
    'Cook or order in something special for dinner. ',
    "Put a loving note, a treat, or a small gift on your partner's pillow, so they see it before bed. ",
    'Mornings can be hectic. Make the next one a little easier by texting your partner an encouraging note on your way to work. ',
    "When your partner solves a mini crisis, whether it's an overdue bill or a screaming child, let them know they handled it well. ",
    'Before you go to bed, ask your partner, <break time="0.05s"/>"What are you most proud of today?" ',
    'Before you go to bed, ask your partner, <break time="0.05s"/>"What are you most excited for tomorrow?" ',
    'Ask your significant other for advice in one area, and then take it. ',
    'Before you go to bed, fill in the blank and tell your significant other, <break time="0.05s"/>"I thought you did a great job on blank today. " ',
    'Encourage your partner to spend time just with their friends. ',
    'If you can, surprise your significant other with a clean car and a full tank of gas. ',
    'Fill in the blank and say to your partner, <break time="0.05s"/>"You know, if it weren\'t for you, I couldn\'t do blank." ',
    "Go out for a spontaneous drink or dessert this evening. ",
    "Put your partner's favorite song on when you can both hear it. ",
    
];
